create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null,
  industry text not null default '未分類',
  status text not null default '洽談中',
  consultant text not null,
  contact text not null default '—',
  email text not null default '',
  phone text not null default '',
  expectations text not null default '尚未填寫',
  pain_points text not null default '尚未填寫',
  last_interaction date not null default current_date,
  next_follow_up date not null default current_date + 7,
  health text not null default '健康',
  color text not null default '#477467',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contracts (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.clients(id) on delete cascade,
  name text not null,
  content text not null default '尚未填寫',
  topic text not null default '未分類',
  start_date date not null,
  end_date date not null,
  amount numeric(14,2) not null default 0,
  status text not null default '有效',
  hours numeric(8,2) not null default 0,
  used_hours numeric(8,2) not null default 0,
  renewal_stage text not null default '未評估',
  probability integer not null default 20 check (probability between 0 and 100),
  renewal_plan text not null default '尚未規劃',
  next_action text not null default '評估續約可能性',
  next_action_date date not null default current_date + 30,
  renewal_owner text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  client_id bigint not null references public.clients(id) on delete cascade,
  assignee text not null,
  due_date date not null,
  priority text not null default '中',
  status text not null default '待處理',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists contracts_client_id_idx on public.contracts(client_id);
create index if not exists contracts_end_date_idx on public.contracts(end_date);
create index if not exists contracts_renewal_stage_idx on public.contracts(renewal_stage);
create index if not exists tasks_client_id_idx on public.tasks(client_id);
create index if not exists tasks_due_date_idx on public.tasks(due_date);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists clients_set_updated_at on public.clients;
create trigger clients_set_updated_at
before update on public.clients
for each row execute function public.set_updated_at();

drop trigger if exists contracts_set_updated_at on public.contracts;
create trigger contracts_set_updated_at
before update on public.contracts
for each row execute function public.set_updated_at();

drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at
before update on public.tasks
for each row execute function public.set_updated_at();

alter table public.clients enable row level security;
alter table public.contracts enable row level security;
alter table public.tasks enable row level security;

drop policy if exists "public read clients" on public.clients;
drop policy if exists "public insert clients" on public.clients;
drop policy if exists "public update clients" on public.clients;
drop policy if exists "authenticated read clients" on public.clients;
drop policy if exists "authenticated insert clients" on public.clients;
drop policy if exists "authenticated update clients" on public.clients;
drop policy if exists "admin read clients" on public.clients;
drop policy if exists "admin insert clients" on public.clients;
drop policy if exists "admin update clients" on public.clients;
create policy "admin read clients" on public.clients for select to authenticated using ((auth.jwt() ->> 'email') = 'raychen9@gmail.com');
create policy "admin insert clients" on public.clients for insert to authenticated with check ((auth.jwt() ->> 'email') = 'raychen9@gmail.com');
create policy "admin update clients" on public.clients for update to authenticated using ((auth.jwt() ->> 'email') = 'raychen9@gmail.com') with check ((auth.jwt() ->> 'email') = 'raychen9@gmail.com');

drop policy if exists "public read contracts" on public.contracts;
drop policy if exists "public insert contracts" on public.contracts;
drop policy if exists "public update contracts" on public.contracts;
drop policy if exists "authenticated read contracts" on public.contracts;
drop policy if exists "authenticated insert contracts" on public.contracts;
drop policy if exists "authenticated update contracts" on public.contracts;
drop policy if exists "admin read contracts" on public.contracts;
drop policy if exists "admin insert contracts" on public.contracts;
drop policy if exists "admin update contracts" on public.contracts;
create policy "admin read contracts" on public.contracts for select to authenticated using ((auth.jwt() ->> 'email') = 'raychen9@gmail.com');
create policy "admin insert contracts" on public.contracts for insert to authenticated with check ((auth.jwt() ->> 'email') = 'raychen9@gmail.com');
create policy "admin update contracts" on public.contracts for update to authenticated using ((auth.jwt() ->> 'email') = 'raychen9@gmail.com') with check ((auth.jwt() ->> 'email') = 'raychen9@gmail.com');

drop policy if exists "public read tasks" on public.tasks;
drop policy if exists "public insert tasks" on public.tasks;
drop policy if exists "public update tasks" on public.tasks;
drop policy if exists "authenticated read tasks" on public.tasks;
drop policy if exists "authenticated insert tasks" on public.tasks;
drop policy if exists "authenticated update tasks" on public.tasks;
drop policy if exists "admin read tasks" on public.tasks;
drop policy if exists "admin insert tasks" on public.tasks;
drop policy if exists "admin update tasks" on public.tasks;
create policy "admin read tasks" on public.tasks for select to authenticated using ((auth.jwt() ->> 'email') = 'raychen9@gmail.com');
create policy "admin insert tasks" on public.tasks for insert to authenticated with check ((auth.jwt() ->> 'email') = 'raychen9@gmail.com');
create policy "admin update tasks" on public.tasks for update to authenticated using ((auth.jwt() ->> 'email') = 'raychen9@gmail.com') with check ((auth.jwt() ->> 'email') = 'raychen9@gmail.com');
